# this is the rendering backend
backend = "xrender";

# transparency settings
# alacritty doesnt change opacity unless
# i set it explicitly here
active-opacity = 1.0;

# fading settings
fading = true;
fade-in-step = 0.03;
fade-out-step = 0.03;
fade-delta = 4;
