#################################
#             Shadows           #
#################################
shadow = true;
shadow-radius = 7;
shadow-offset-x = -7;
shadow-offset-y = -7;
shadow-exclude = [
  "name = 'Notification'",
  "class_g = 'Conky'",
  "class_g ?= 'Notify-osd'",
  "class_g = 'Cairo-clock'",
  "_GTK_FRAME_EXTENTS@:c"
];

# clip-shadow-above = []
# shadow-exclude-reg = ""

# xinerama-shadow-crop = false


#################################
#           Fading              #
#################################


fading = true;
fade-in-step = 0.03;

# Opacity change between steps while fading out. (0.01 - 1.0, defaults to 0.03)
# fade-out-step = 0.03
fade-out-step = 0.03;
fade-delta = 8

# Specify a list of conditions of windows that should not be faded.
# fade-exclude = []

#################################
#   Transparency / Opacity      #
#################################

inactive-opacity = 1;
frame-opacity = 1;
inactive-opacity-override = false;
active-opacity = 1;
# inactive-dim = 0.0

opacity-rule = [
    "85:class_g = 'Alacritty' && focused",
    "70:class_g = 'Alacritty' && !focused"
];



# Specify a list of conditions of windows that should never be considered focused.
# focus-exclude = []
focus-exclude = [ "class_g = 'Cairo-clock'" ];


#################################
#           Corners             #
#################################

# `transparent-clipping`.
corner-radius = 10;

rounded-corners-exclude = [
  "window_type = 'dock'",
  "window_type = 'desktop'"
];


#################################
#     Background-Blurring       #
#################################


# Parameters for background blurring, see the *BLUR* section for more information.
blur-method = "dual_kawase"
blur-strength = 6
blur-background-frame = true;

# blur-background-exclude = []
blur-background-exclude = [
  "window_type = 'desktop'",
  "_GTK_FRAME_EXTENTS@:c",
  "role = 'xborder'"
];

#################################
#       General Settings        #
#################################

backend = "glx"
# backend = "xrender";

vsync = true;
log-level = "warn";

wintypes:
{
  tooltip = { fade = true; shadow = true; opacity = 0.75; focus = true; full-shadow = false; };
  dock = { blur-background = true; shadow = false; clip-shadow-above = true; }
  dnd = { shadow = false; }
  popup_menu = { opacity = 0.8; }
  dropdown_menu = { opacity = 0.8; }
};



